// ============================================================
//  StudyBell Push Server
//  Deploy FREE on Render.com (Web Service, Node runtime)
//
//  Environment variables to set on Render.com:
//    VAPID_PUBLIC_KEY   — generated by web-push (see README below)
//    VAPID_PRIVATE_KEY  — generated by web-push
//    VAPID_EMAIL        — mailto:you@example.com
//
//  Local dev:
//    npm install
//    npm start
// ============================================================

const express  = require('express');
const webpush  = require('web-push');
const cors     = require('cors');

const app = express();
app.use(express.json());

// Allow requests from any origin (your GitHub Pages / Firebase Hosting site)
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type']
}));

// ── VAPID setup ────────────────────────────────────────────
const VAPID_PUBLIC_KEY  = process.env.VAPID_PUBLIC_KEY;
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY;
const VAPID_EMAIL       = process.env.VAPID_EMAIL || 'mailto:studybell@example.com';

if (!VAPID_PUBLIC_KEY || !VAPID_PRIVATE_KEY) {
  console.error('❌  Missing VAPID_PUBLIC_KEY or VAPID_PRIVATE_KEY env vars.');
  console.error('    Run:  node -e "const wp=require(\'web-push\'); console.log(JSON.stringify(wp.generateVAPIDKeys()))"');
  console.error('    Then set both keys as env vars on Render.com.');
  process.exit(1);
}

webpush.setVapidDetails(VAPID_EMAIL, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY);

// ── Health check ───────────────────────────────────────────
app.get('/', (_req, res) => {
  res.json({ status: 'ok', service: 'StudyBell Push Server 🔔' });
});

// ── Return VAPID public key to client ─────────────────────
// The browser needs this to create a push subscription.
app.get('/vapid-public-key', (_req, res) => {
  res.json({ publicKey: VAPID_PUBLIC_KEY });
});

// ── Send push notification ─────────────────────────────────
// Called by StudyBell sender when a signal is dispatched.
// Body: { subscription, title, body, icon, badge, vibrate, tag }
app.post('/send-push', async (req, res) => {
  const { subscription, title, body, icon, badge, vibrate, tag } = req.body;

  if (!subscription) {
    return res.status(400).json({ error: 'Missing subscription object' });
  }

  const payload = JSON.stringify({
    title:   title   || '🔔 StudyBell',
    body:    body    || 'You have a new signal!',
    icon:    icon    || '/icon-192.png',
    badge:   badge   || '/icon-192.png',
    vibrate: vibrate || [200, 100, 200],
    tag:     tag     || 'studybell-signal'
  });

  try {
    await webpush.sendNotification(subscription, payload, {
      TTL: 60,          // If receiver is offline, retry for 60 seconds
      urgency: 'high'   // Tell browser to deliver immediately
    });
    console.log(`[${new Date().toISOString()}] Push sent: ${title}`);
    res.json({ success: true });
  } catch (err) {
    console.error('Push error:', err.statusCode, err.body);

    // 410 Gone = subscription expired / user unsubscribed
    if (err.statusCode === 410 || err.statusCode === 404) {
      return res.status(410).json({ error: 'Subscription expired. Receiver needs to re-enable notifications.' });
    }
    res.status(500).json({ error: err.message || 'Push failed' });
  }
});

// ── Start ──────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🔔 StudyBell push server running on port ${PORT}`);
});

// ============================================================
//  README — How to deploy on Render.com (free tier)
// ============================================================
/*

STEP 1 — Generate VAPID keys (run once on your PC or in Render shell)
─────────────────────────────────────────────────────────────────────
  npm install web-push -g
  web-push generate-vapid-keys

  You'll get:
    Public Key:  Bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Private Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

STEP 2 — Create a GitHub repo with these files
──────────────────────────────────────────────
  server.js        ← this file
  package.json     ← see below

STEP 3 — Deploy on Render.com (free)
──────────────────────────────────────
  1. Go to https://render.com → New → Web Service
  2. Connect your GitHub repo
  3. Runtime: Node
  4. Build Command: npm install
  5. Start Command: node server.js
  6. Add Environment Variables:
       VAPID_PUBLIC_KEY   = (from step 1)
       VAPID_PRIVATE_KEY  = (from step 1)
       VAPID_EMAIL        = mailto:your@email.com
  7. Deploy — you'll get a URL like https://studybell.onrender.com

STEP 4 — Paste the Render.com URL into StudyBell setup screen
─────────────────────────────────────────────────────────────
  Push Server URL:  https://studybell.onrender.com

STEP 5 — Receiver opens app → taps "Enable notifications" banner
────────────────────────────────────────────────────────────────
  The subscription is saved to Firestore automatically.
  From that point, any signal sent by the sender will push
  instantly even if receiver's tab is closed or phone is locked.

⚠️  Render FREE tier sleeps after 15 min of no traffic.
    First push after sleep can take ~30s.
    To avoid this: ping the server every 10 min via UptimeRobot
    (free at https://uptimerobot.com) using URL:
      https://studybell.onrender.com/  (HTTP Monitor, every 5 min)

*/
